/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import filterFile.Filter;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import jdk.nashorn.internal.runtime.Context;

import com.flickr4java.flickr.Flickr;
import com.flickr4java.flickr.FlickrException;
import com.flickr4java.flickr.REST;
import com.flickr4java.flickr.RequestContext;
import com.flickr4java.flickr.groups.Group;
import com.flickr4java.flickr.groups.pools.PoolsInterface;
import com.flickr4java.flickr.photos.PhotoSet;
import com.flickr4java.flickr.photos.PhotosInterface;
import com.flickr4java.flickr.photos.upload.Ticket;
import com.flickr4java.flickr.photos.upload.UploadInterface;
import com.flickr4java.flickr.photosets.Photoset;
import com.flickr4java.flickr.photosets.PhotosetsInterface;
import com.flickr4java.flickr.prefs.PrefsInterface;
import com.flickr4java.flickr.uploader.UploadMetaData;
import com.flickr4java.flickr.uploader.Uploader;
import com.mycompany.flickerdistribuidos.FlickrHelper.Imagenes;
import com.mycompany.flickerdistribuidos.Main;
import com.urjc.java.pruautorizacionesflickr.AutorizacionesFlickr;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Scanner;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author Alberto
 */
public class GUI extends javax.swing.JFrame {

    private String [] ficheros;
    private File directorio;
    static Flickr flickr;
    private Imagenes subir;
    ArrayList<Group> grupos;

    static Set<String> pids = new HashSet<>();
    final static AutorizacionesFlickr autorizacionesFlickr
            = new AutorizacionesFlickr();
    
    public class Imagen extends javax.swing.JPanel {
 
        private final String img;
        
        public Imagen(int x, int y, String img) {
            this.setSize(x, y);
            this.img = img;//se selecciona el tamaño del panel         
        }
 
        //Se crea un método cuyo parámetro debe ser un objeto Graphics
 
        @Override
        public void paint(Graphics grafico) {
            Dimension height = getSize();
 
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getClassLoader().getResource(this.img));
            
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
 
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }
    
    /**
     * Creates new form GUIInicio
     */
    public GUI() {
        initComponents();          
        
        flickr
                = new Flickr(autorizacionesFlickr.getApi_key(),
                        autorizacionesFlickr.getSecret(),
                        new REST());
        RequestContext rContext = RequestContext.getRequestContext();
        rContext.setAuth(autorizacionesFlickr.getAuth());
        subir = new Imagenes(flickr);               
        
        //Pantalla Inicio
        pantallaInicio.setVisible(true);
        Imagen imgInicio = new Imagen(580, 490,"flickr-inicio.png");
        pantallaInicio.add(imgInicio);
        pantallaInicio.repaint();        
        
        //Oculta el resto de paneles        
        panelSelectorDirectorio.setVisible(false);
        pantallaListar.setVisible(false);
        pantallaSubir.setVisible(false);
        cuadroTextoEtiquetasSubir.setEditable(false);
        pantallaAlbumGrupo.setVisible(false);
        
        //Hace que el Selector de ficheros solo muestre directorios
        selectorDirectorio.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        //Hace que el textArea que muestra la lista de archivos a subir no se
        //pueda modificar
        listadoArchivosListar.setEditable(false);
        listadoArchivosSubir.setEditable(false);
        cuadroTextoEtiquetasSubir.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capaspantallaInicio = new javax.swing.JLayeredPane();
        pantallaInicio = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        capaspanelSelectorDirectorio = new javax.swing.JLayeredPane();
        panelSelectorDirectorio = new javax.swing.JPanel();
        selectorDirectorio = new javax.swing.JFileChooser();
        capaspantallaListar = new javax.swing.JLayeredPane();
        pantallaListar = new javax.swing.JPanel();
        botonListarSubirArchivos = new javax.swing.JButton();
        cancelarListar = new javax.swing.JButton();
        cuadroTextoEtiquetasListar = new javax.swing.JTextField();
        labelEtiquetasListar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadoArchivosListar = new javax.swing.JTextArea();
        labelTContenido = new javax.swing.JLabel();
        jComboBoxPrivacidad = new javax.swing.JComboBox();
        labelPrivacidad = new javax.swing.JLabel();
        jComboBoxTContenido = new javax.swing.JComboBox();
        labelSeguridad = new javax.swing.JLabel();
        jComboBoxSeguridad = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        capaspantallaSubir = new javax.swing.JLayeredPane();
        pantallaSubir = new javax.swing.JPanel();
        terminarSubir = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        cuadroTextoEtiquetasSubir = new javax.swing.JTextField();
        labelEtiquetasSubir = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listadoArchivosSubir = new javax.swing.JTextArea();
        capaspantallaAlbumGrupo = new javax.swing.JLayeredPane();
        pantallaAlbumGrupo = new javax.swing.JPanel();
        guardarAlbumGrupo = new javax.swing.JButton();
        panelAlbum = new javax.swing.JPanel();
        labelNombreAlbum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionAlbum = new javax.swing.JTextArea();
        labelDescripcionAlbum = new javax.swing.JLabel();
        textoAlbumNuevo = new javax.swing.JTextField();
        panelGrupos = new javax.swing.JPanel();
        labelGrupo = new javax.swing.JLabel();
        jComboBoxGrupos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        informacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));

        capaspantallaInicio.setMaximumSize(new java.awt.Dimension(600, 600));
        capaspantallaInicio.setMinimumSize(new java.awt.Dimension(600, 600));

        pantallaInicio.setMaximumSize(new java.awt.Dimension(600, 600));
        pantallaInicio.setPreferredSize(new java.awt.Dimension(600, 600));

        botonInicio.setText("Subir Fotos");
        botonInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonInicio.setMaximumSize(new java.awt.Dimension(80, 23));
        botonInicio.setMinimumSize(new java.awt.Dimension(80, 23));
        botonInicio.setPreferredSize(new java.awt.Dimension(80, 23));
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaInicioLayout = new javax.swing.GroupLayout(pantallaInicio);
        pantallaInicio.setLayout(pantallaInicioLayout);
        pantallaInicioLayout.setHorizontalGroup(
            pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaInicioLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        pantallaInicioLayout.setVerticalGroup(
            pantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaInicioLayout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout capaspantallaInicioLayout = new javax.swing.GroupLayout(capaspantallaInicio);
        capaspantallaInicio.setLayout(capaspantallaInicioLayout);
        capaspantallaInicioLayout.setHorizontalGroup(
            capaspantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        capaspantallaInicioLayout.setVerticalGroup(
            capaspantallaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capaspantallaInicioLayout.createSequentialGroup()
                .addComponent(pantallaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        capaspantallaInicio.setLayer(pantallaInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        capaspanelSelectorDirectorio.setMaximumSize(new java.awt.Dimension(600, 600));
        capaspanelSelectorDirectorio.setMinimumSize(new java.awt.Dimension(600, 600));

        panelSelectorDirectorio.setMaximumSize(new java.awt.Dimension(600, 600));
        panelSelectorDirectorio.setMinimumSize(new java.awt.Dimension(600, 600));
        panelSelectorDirectorio.setPreferredSize(new java.awt.Dimension(600, 600));

        selectorDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorDirectorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectorDirectorioLayout = new javax.swing.GroupLayout(panelSelectorDirectorio);
        panelSelectorDirectorio.setLayout(panelSelectorDirectorioLayout);
        panelSelectorDirectorioLayout.setHorizontalGroup(
            panelSelectorDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectorDirectorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectorDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelSelectorDirectorioLayout.setVerticalGroup(
            panelSelectorDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectorDirectorioLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(selectorDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout capaspanelSelectorDirectorioLayout = new javax.swing.GroupLayout(capaspanelSelectorDirectorio);
        capaspanelSelectorDirectorio.setLayout(capaspanelSelectorDirectorioLayout);
        capaspanelSelectorDirectorioLayout.setHorizontalGroup(
            capaspanelSelectorDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capaspanelSelectorDirectorioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelSelectorDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        capaspanelSelectorDirectorioLayout.setVerticalGroup(
            capaspanelSelectorDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capaspanelSelectorDirectorioLayout.createSequentialGroup()
                .addComponent(panelSelectorDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        capaspanelSelectorDirectorio.setLayer(panelSelectorDirectorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        capaspantallaListar.setMaximumSize(new java.awt.Dimension(600, 589));
        capaspantallaListar.setMinimumSize(new java.awt.Dimension(600, 589));

        pantallaListar.setMaximumSize(new java.awt.Dimension(600, 589));
        pantallaListar.setMinimumSize(new java.awt.Dimension(600, 589));
        pantallaListar.setPreferredSize(new java.awt.Dimension(600, 589));

        botonListarSubirArchivos.setText("Subir archivos");
        botonListarSubirArchivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonListarSubirArchivos.setMaximumSize(new java.awt.Dimension(80, 23));
        botonListarSubirArchivos.setMinimumSize(new java.awt.Dimension(80, 23));
        botonListarSubirArchivos.setPreferredSize(new java.awt.Dimension(80, 23));
        botonListarSubirArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarSubirArchivosActionPerformed(evt);
            }
        });

        cancelarListar.setText("Cancelar");
        cancelarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarListarActionPerformed(evt);
            }
        });

        cuadroTextoEtiquetasListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroTextoEtiquetasListarActionPerformed(evt);
            }
        });

        labelEtiquetasListar.setText("Etiquetas:");

        listadoArchivosListar.setColumns(20);
        listadoArchivosListar.setRows(5);
        jScrollPane2.setViewportView(listadoArchivosListar);

        labelTContenido.setText("Tipo de contenido:");

        jComboBoxPrivacidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Familia", "Familia y amigos", "Privado" }));
        jComboBoxPrivacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivacidadActionPerformed(evt);
            }
        });

        labelPrivacidad.setText("Privacidad:");

        jComboBoxTContenido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Foto", "Captura de pantalla", "Otro" }));
        jComboBoxTContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTContenidoActionPerformed(evt);
            }
        });

        labelSeguridad.setText("Seguridad:");

        jComboBoxSeguridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seguro", "Moderado", "Restringido" }));

        jLabel2.setText("Las etiquetas deben estar separadas por comas");

        javax.swing.GroupLayout pantallaListarLayout = new javax.swing.GroupLayout(pantallaListar);
        pantallaListar.setLayout(pantallaListarLayout);
        pantallaListarLayout.setHorizontalGroup(
            pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaListarLayout.createSequentialGroup()
                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pantallaListarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaListarLayout.createSequentialGroup()
                                .addComponent(cancelarListar)
                                .addGap(18, 18, 18)
                                .addComponent(botonListarSubirArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaListarLayout.createSequentialGroup()
                                .addComponent(labelEtiquetasListar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cuadroTextoEtiquetasListar, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pantallaListarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantallaListarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrivacidad)
                                    .addComponent(jComboBoxPrivacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTContenido)
                                    .addComponent(jComboBoxTContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSeguridad)
                                    .addComponent(jComboBoxSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pantallaListarLayout.setVerticalGroup(
            pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaListarLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxPrivacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pantallaListarLayout.createSequentialGroup()
                        .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrivacidad)
                            .addComponent(labelTContenido)
                            .addComponent(labelSeguridad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroTextoEtiquetasListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEtiquetasListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonListarSubirArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarListar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout capaspantallaListarLayout = new javax.swing.GroupLayout(capaspantallaListar);
        capaspantallaListar.setLayout(capaspantallaListarLayout);
        capaspantallaListarLayout.setHorizontalGroup(
            capaspantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        capaspantallaListarLayout.setVerticalGroup(
            capaspantallaListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capaspantallaListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantallaListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capaspantallaListar.setLayer(pantallaListar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        capaspantallaSubir.setMaximumSize(new java.awt.Dimension(600, 600));
        capaspantallaSubir.setMinimumSize(new java.awt.Dimension(600, 600));

        pantallaSubir.setMaximumSize(new java.awt.Dimension(600, 589));
        pantallaSubir.setMinimumSize(new java.awt.Dimension(600, 589));
        pantallaSubir.setPreferredSize(new java.awt.Dimension(600, 589));

        terminarSubir.setText("Terminar");
        terminarSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarSubirActionPerformed(evt);
            }
        });

        botonSiguiente.setText("Elegir Álbum/Grupo");
        botonSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSiguiente.setMaximumSize(new java.awt.Dimension(80, 23));
        botonSiguiente.setMinimumSize(new java.awt.Dimension(80, 23));
        botonSiguiente.setPreferredSize(new java.awt.Dimension(80, 23));
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        cuadroTextoEtiquetasSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroTextoEtiquetasSubirActionPerformed(evt);
            }
        });

        labelEtiquetasSubir.setText("Etiquetas:");

        listadoArchivosSubir.setColumns(20);
        listadoArchivosSubir.setRows(5);
        jScrollPane3.setViewportView(listadoArchivosSubir);

        javax.swing.GroupLayout pantallaSubirLayout = new javax.swing.GroupLayout(pantallaSubir);
        pantallaSubir.setLayout(pantallaSubirLayout);
        pantallaSubirLayout.setHorizontalGroup(
            pantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaSubirLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(pantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaSubirLayout.createSequentialGroup()
                            .addComponent(terminarSubir)
                            .addGap(18, 18, 18)
                            .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaSubirLayout.createSequentialGroup()
                            .addComponent(labelEtiquetasSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cuadroTextoEtiquetasSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pantallaSubirLayout.setVerticalGroup(
            pantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaSubirLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroTextoEtiquetasSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEtiquetasSubir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminarSubir))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout capaspantallaSubirLayout = new javax.swing.GroupLayout(capaspantallaSubir);
        capaspantallaSubir.setLayout(capaspantallaSubirLayout);
        capaspantallaSubirLayout.setHorizontalGroup(
            capaspantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, capaspantallaSubirLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pantallaSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        capaspantallaSubirLayout.setVerticalGroup(
            capaspantallaSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capaspantallaSubirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantallaSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capaspantallaSubir.setLayer(pantallaSubir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        capaspantallaAlbumGrupo.setMaximumSize(new java.awt.Dimension(600, 589));
        capaspantallaAlbumGrupo.setMinimumSize(new java.awt.Dimension(600, 589));

        pantallaAlbumGrupo.setMaximumSize(new java.awt.Dimension(600, 589));
        pantallaAlbumGrupo.setMinimumSize(new java.awt.Dimension(600, 589));
        pantallaAlbumGrupo.setPreferredSize(new java.awt.Dimension(600, 589));

        guardarAlbumGrupo.setText("Añadir a Álbum");
        guardarAlbumGrupo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarAlbumGrupo.setMaximumSize(new java.awt.Dimension(80, 23));
        guardarAlbumGrupo.setMinimumSize(new java.awt.Dimension(80, 23));
        guardarAlbumGrupo.setPreferredSize(new java.awt.Dimension(80, 23));
        guardarAlbumGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlbumGrupoActionPerformed(evt);
            }
        });

        panelAlbum.setBorder(javax.swing.BorderFactory.createTitledBorder("Álbum"));
        panelAlbum.setMaximumSize(new java.awt.Dimension(550, 200));
        panelAlbum.setMinimumSize(new java.awt.Dimension(550, 200));
        panelAlbum.setPreferredSize(new java.awt.Dimension(550, 200));

        labelNombreAlbum.setText("Nombre del Álbum:");

        descripcionAlbum.setColumns(20);
        descripcionAlbum.setRows(5);
        jScrollPane1.setViewportView(descripcionAlbum);

        labelDescripcionAlbum.setText("Descipción del Álbum:");

        textoAlbumNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAlbumNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlbumLayout = new javax.swing.GroupLayout(panelAlbum);
        panelAlbum.setLayout(panelAlbumLayout);
        panelAlbumLayout.setHorizontalGroup(
            panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(panelAlbumLayout.createSequentialGroup()
                        .addGroup(panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoAlbumNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDescripcionAlbum))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAlbumLayout.setVerticalGroup(
            panelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNombreAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoAlbumNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDescripcionAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo"));
        panelGrupos.setMaximumSize(new java.awt.Dimension(550, 100));
        panelGrupos.setMinimumSize(new java.awt.Dimension(550, 100));
        panelGrupos.setPreferredSize(new java.awt.Dimension(550, 100));

        labelGrupo.setText("Grupo:");

        jComboBoxGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGruposActionPerformed(evt);
            }
        });

        jButton1.setText("Añadir a Grupo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>Si quiere que se incluya en algún grupo, seleccione un grupo y pulse Añadir a Grupo.</html>");

        javax.swing.GroupLayout panelGruposLayout = new javax.swing.GroupLayout(panelGrupos);
        panelGrupos.setLayout(panelGruposLayout);
        panelGruposLayout.setHorizontalGroup(
            panelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGruposLayout.createSequentialGroup()
                        .addComponent(jComboBoxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(labelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGruposLayout.setVerticalGroup(
            panelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout pantallaAlbumGrupoLayout = new javax.swing.GroupLayout(pantallaAlbumGrupo);
        pantallaAlbumGrupo.setLayout(pantallaAlbumGrupoLayout);
        pantallaAlbumGrupoLayout.setHorizontalGroup(
            pantallaAlbumGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaAlbumGrupoLayout.createSequentialGroup()
                .addGroup(pantallaAlbumGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pantallaAlbumGrupoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(informacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pantallaAlbumGrupoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pantallaAlbumGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(guardarAlbumGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        pantallaAlbumGrupoLayout.setVerticalGroup(
            pantallaAlbumGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaAlbumGrupoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(panelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(guardarAlbumGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout capaspantallaAlbumGrupoLayout = new javax.swing.GroupLayout(capaspantallaAlbumGrupo);
        capaspantallaAlbumGrupo.setLayout(capaspantallaAlbumGrupoLayout);
        capaspantallaAlbumGrupoLayout.setHorizontalGroup(
            capaspantallaAlbumGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capaspantallaAlbumGrupoLayout.createSequentialGroup()
                .addComponent(pantallaAlbumGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        capaspantallaAlbumGrupoLayout.setVerticalGroup(
            capaspantallaAlbumGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capaspantallaAlbumGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantallaAlbumGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capaspantallaAlbumGrupo.setLayer(pantallaAlbumGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(capaspantallaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspanelSelectorDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspantallaListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspantallaSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspantallaAlbumGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(capaspantallaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspanelSelectorDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspantallaListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspantallaSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(capaspantallaAlbumGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
        pantallaInicio.setVisible(false);
        
        panelSelectorDirectorio.setVisible(true);
        Imagen imgLogo = new Imagen(600, 88,"flickr-logo.png");
        panelSelectorDirectorio.add(imgLogo);
        panelSelectorDirectorio.repaint();
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonListarSubirArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarSubirArchivosActionPerformed
        // TODO add your handling code here:
        
        String photoID;        
                      
        String tags = (cuadroTextoEtiquetasListar.getText());
            
        cuadroTextoEtiquetasSubir.setText(tags);
        cuadroTextoEtiquetasListar.setEditable(false);
        botonListarSubirArchivos.setEnabled(false);
        cancelarListar.setEnabled(false);
        
        listadoArchivosListar.append(("\n" + "-------------------------------------------" 
                                      + "\n" + "Subiendo Archivos:\n"));
                             
        
                       
        try {
            //Set<String> photosIds = subir.Upload_photos(directorio.listFiles(IMAGE_FILTER), 1, 1, 1, tags);
            Set<String> photosIds = subir.Upload_photos(directorio.listFiles(Filter.IMAGE_FILTER), jComboBoxPrivacidad.getSelectedIndex(),
                                                        jComboBoxSeguridad.getSelectedIndex(), jComboBoxTContenido.getSelectedIndex(), tags);
            Thread t = new Thread(new Runnable() {

                @Override
                public void run() {
                    subir.ComprobarSubida(listadoArchivosListar);
                }
            });
            t.start();                                                                                                       
                
        } catch (FlickrException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        botonListarSubirArchivos.setEnabled(true);
        cancelarListar.setEnabled(true);
        listadoArchivosSubir.setText(listadoArchivosListar.getText());
        cuadroTextoEtiquetasListar.setEditable(true);
        cuadroTextoEtiquetasListar.setText("");
        
        //Pantalla fin de subida
        pantallaListar.setVisible(false);
        pantallaSubir.setVisible(true);        
        Imagen imgLogo = new Imagen(600, 88,"flickr-logo.png");
        pantallaSubir.add(imgLogo);
        pantallaSubir.repaint();
        
        
        //botonSiguiente.setEnabled(true);
            
    }//GEN-LAST:event_botonListarSubirArchivosActionPerformed

    private void cancelarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarListarActionPerformed
        // TODO add your handling code here:
        System.out.println("Se ha pulsado el botón Cancelar.");
        
        //Borra el listado de archivos del textArea
        listadoArchivosListar.setText("");
        cuadroTextoEtiquetasListar.setText("");
        
        //Vuelve a la pantalla de inicio
        //Pantalla Inicio
        pantallaInicio.setVisible(true);             
        
        //Oculta el resto de paneles                
        pantallaListar.setVisible(false);
    }//GEN-LAST:event_cancelarListarActionPerformed

    private void cuadroTextoEtiquetasListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroTextoEtiquetasListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroTextoEtiquetasListarActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // TODO add your handling code here:
        pantallaSubir.setVisible(false);
        
        textoAlbumNuevo.setText(directorio.getName());
        descripcionAlbum.setText("");        
        pantallaAlbumGrupo.setVisible(true);
        Imagen imgLogo = new Imagen(600, 88,"flickr-logo.png");
        pantallaAlbumGrupo.add(imgLogo);
        pantallaAlbumGrupo.repaint();
        
        //Recupera los grupos
        try {
            grupos = new ArrayList(subir.getGrupos());
            //String [] gruposJBox = new String[grupos.size()];
            /*for (int i=0; i<grupos.size(); i++) {
                //gruposJBox[i] = grupos.get(i).getName();
                jComboBoxGrupos.addItem(grupos.get(i).getName());
            } */   
            for (Group grupo : grupos) {
                //gruposJBox[i] = grupos.get(i).getName();
                jComboBoxGrupos.addItem(grupo.getName());
            }
            //jComboBoxGrupos = new JComboBox(gruposJBox);
            
        } catch (FlickrException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }               
        
        //Borra el listado de archivos del textArea
        listadoArchivosSubir.setText("");
        cuadroTextoEtiquetasSubir.setText("");
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void cuadroTextoEtiquetasSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroTextoEtiquetasSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroTextoEtiquetasSubirActionPerformed

    private void terminarSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarSubirActionPerformed
        // TODO add your handling code here:
        try {
            subir.publicarAlbum("Fotos", "Álbum creado por defecto");
        } catch (FlickrException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Borra el listado de archivos del textArea
        listadoArchivosSubir.setText("");
        cuadroTextoEtiquetasSubir.setText("");
        
        //Vuelve a la pantalla de inicio
        //Pantalla Inicio
        pantallaInicio.setVisible(true);             
        
        //Oculta el resto de paneles                
        pantallaSubir.setVisible(false);
        
    }//GEN-LAST:event_terminarSubirActionPerformed

    private void guardarAlbumGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlbumGrupoActionPerformed
        // TODO add your handling code here:
        try {
            subir.publicarAlbum(textoAlbumNuevo.getText(),descripcionAlbum.getText());
                        
        } catch (FlickrException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }        

        
        //Pantalla Inicio
        pantallaInicio.setVisible(true);             
        
        //Oculta el resto de paneles                
        pantallaAlbumGrupo.setVisible(false);
    }//GEN-LAST:event_guardarAlbumGrupoActionPerformed

    private void textoAlbumNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAlbumNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAlbumNuevoActionPerformed

    private void selectorDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorDirectorioActionPerformed
        // TODO add your handling code here:
        String seleccion = evt.getActionCommand();

        if (seleccion.equals(JFileChooser.APPROVE_SELECTION)) {
            System.out.println("Directorio actual: "
                +  selectorDirectorio.getCurrentDirectory());
            System.out.println("Directorio seleccionado: "
                +  selectorDirectorio.getSelectedFile());

            directorio = selectorDirectorio.getSelectedFile();

            //Filtra las imagenes del directorio
            ficheros = Filter.filtroImagenes(directorio);

            for (int i=0; i<ficheros.length; i++) {
                ficheros[i] = directorio + "\\" + ficheros[i];
            }

            System.out.println("Archivos seleccionados:");
            for (String fichero : ficheros) {
                listadoArchivosListar.append(fichero + "\n");
                System.out.println(fichero);
            }

            //Oculta el panel selector de archivos y muestra el listado
            //de archivos
            panelSelectorDirectorio.setVisible(false);

            pantallaListar.setVisible(true);
            Imagen imgLogo = new Imagen(600, 88,"flickr-logo.png");
            pantallaListar.add(imgLogo);
            pantallaListar.repaint();

        } else if (seleccion.equals(JFileChooser.CANCEL_SELECTION)) {
            System.out.println("Se ha pulsado el botón Cancelar.");
            //Vuelve a la pantalla de inicio
            //Pantalla Inicio
            pantallaInicio.setVisible(true);

            //Oculta el resto de paneles
            panelSelectorDirectorio.setVisible(false);
        }

    }//GEN-LAST:event_selectorDirectorioActionPerformed

    private void jComboBoxGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGruposActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Group grupo = grupos.get(jComboBoxGrupos.getSelectedIndex());
            
        try {
            subir.publicarEnGrupo(grupo);
            informacionLabel.setText("<html>Fotos añadidas al grupo con éxito.</html>");
        } catch (FlickrException ex) {
            informacionLabel.setText("<html>Error al añadir las fotos al grupo seleccionado.</html>");
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTContenidoActionPerformed

    private void jComboBoxPrivacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPrivacidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonListarSubirArchivos;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton cancelarListar;
    private javax.swing.JLayeredPane capaspanelSelectorDirectorio;
    private javax.swing.JLayeredPane capaspantallaAlbumGrupo;
    private javax.swing.JLayeredPane capaspantallaInicio;
    private javax.swing.JLayeredPane capaspantallaListar;
    private javax.swing.JLayeredPane capaspantallaSubir;
    private javax.swing.JTextField cuadroTextoEtiquetasListar;
    private javax.swing.JTextField cuadroTextoEtiquetasSubir;
    private javax.swing.JTextArea descripcionAlbum;
    private javax.swing.JButton guardarAlbumGrupo;
    private javax.swing.JLabel informacionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxGrupos;
    private javax.swing.JComboBox jComboBoxPrivacidad;
    private javax.swing.JComboBox jComboBoxSeguridad;
    private javax.swing.JComboBox jComboBoxTContenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDescripcionAlbum;
    private javax.swing.JLabel labelEtiquetasListar;
    private javax.swing.JLabel labelEtiquetasSubir;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelNombreAlbum;
    private javax.swing.JLabel labelPrivacidad;
    private javax.swing.JLabel labelSeguridad;
    private javax.swing.JLabel labelTContenido;
    private javax.swing.JTextArea listadoArchivosListar;
    private javax.swing.JTextArea listadoArchivosSubir;
    private javax.swing.JPanel panelAlbum;
    private javax.swing.JPanel panelGrupos;
    private javax.swing.JPanel panelSelectorDirectorio;
    private javax.swing.JPanel pantallaAlbumGrupo;
    private javax.swing.JPanel pantallaInicio;
    private javax.swing.JPanel pantallaListar;
    private javax.swing.JPanel pantallaSubir;
    private javax.swing.JFileChooser selectorDirectorio;
    private javax.swing.JButton terminarSubir;
    private javax.swing.JTextField textoAlbumNuevo;
    // End of variables declaration//GEN-END:variables

}
